server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost/microservices?useSSL=false&allowMultiQueries=true&serverTimezone=UTC

  config:
    import: optional:configserver:http://localhost:8085




#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-13465540.okta.com/oauth2/default
    audience: api://default