server:
  port: 8084

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**

        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


#OKTA COnfig for api gateway

okta:
  oauth2:
    issuer: https://dev-13465540.okta.com/oauth2/default
    audience: api://default
    client-id: 0oa8865uy7MP7boS25d7
    client-secret: 08Du37h_ynvurdczD3YB1sHfP0QaRdQi-9UClibx
    scopes: openid, profile, email, offline_access